version: '3.1'

services:
  wordpress:
    build: .
    ports:
      - "8080:80" # Maps port 80 on the host to port 80 in the container
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: Pa$$word
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wp-content:/var/www/html/wp-content

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: Pa$$word
      MYSQL_DATABASE: wordpress
    volumes:
      - db_data:/var/lib/mysql

volumes:
  wp-content:
  db_data:
