name: CI/CD Pipeline for WordPress and MySQL

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v2

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Step 3: Build WordPress Image
      - name: Build WordPress Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/wordpress:latest -f ./Dockerfile .

      # Step 4: Push WordPress Image to Docker Hub
      - name: Push WordPress Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/wordpress:latest

      # Step 5: Pull MySQL Image from Docker Hub
      - name: Pull MySQL Image from Docker Hub
        run: docker pull mysql:5.7

      # Step 6: Push MySQL Image to Docker Hub (optional if customized)
      - name: Push MySQL Image (if customized)
        if: ${{ env.MYSQL_IMAGE_CUSTOMIZED == 'true' }}
        run: docker push ${{ secrets.DOCKER_USERNAME }}/mysql:5.7

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Step 7: SSH to EC2 and Deploy
      - name: SSH to EC2 and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}           # EC2 instance public DNS or IP
          username: ubuntu                         # Default username for EC2 Ubuntu AMIs
          key: ${{ secrets.EC2_SSH_KEY }}         # SSH private key stored as a GitHub secret
          script: |
            # Install Docker if not already installed
            if ! command -v docker &> /dev/null; then
              echo "Docker not found, installing Docker..."
              curl -fsSL https://get.docker.com -o get-docker.sh
              sh get-docker.sh
              sudo usermod -aG docker $USER
              newgrp docker
            fi

            # Install Docker Compose if not already installed
            if ! command -v docker-compose &> /dev/null; then
              echo "Docker Compose not found, installing Docker Compose..."
              sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | grep -Po '"tag_name": "\K.*\d')" \
              -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
            fi

            # Log in to Docker Hub on EC2
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

            # Pull the latest images from Docker Hub
            docker pull ${{ secrets.DOCKER_USERNAME }}/wordpress:latest
            docker pull mysql:5.7

            # Start Docker Compose on EC2
            docker-compose -f /path/to/docker-compose.yml up -d
